name: ElytraCore
version: 1.0
main: net.elytrapvp.elytracore.ElytraCore
api-version: 1.16
website: http://www.elytrapvp.met
depend: [PlaceholderAPI]

permission-message: &noperms "§c§lError §8» §cYou do not have access to that command."

 #####
#     #  ####  #    # #    #   ##   #    # #####   ####
#       #    # ##  ## ##  ##  #  #  ##   # #    # #
#       #    # # ## # # ## # #    # # #  # #    #  ####
#       #    # #    # #    # ###### #  # # #    #      #
#     # #    # #    # #    # #    # #   ## #    # #    #
 #####   ####  #    # #    # #    # #    # #####   ####
commands:
  alts:
    permission: elytracore.alts
    permission-message: *noperms
  broadcast:
    aliases: [ bc,announce,a ]
    permission: elytracore.broadcast
    permission-message: *noperms
  chatlog:
    aliases: [cl]
    permission: elytracore.chatlog
    permission-message: *noperms
  clearchat:
    aliases: [cc]
    permission: elytracore.clearchat
    permission-message: *noperms
  commandspy:
    aliases: [cmdspy,cspy]
    permission: elytracore.commandspy
    permission-message: *noperms
  ecsee:
    permission: elytracore.ecsee
    permission-message: *noperms
  enderchest:
    aliases: [ec]
    permission: elytracore.enderchest
    permission-message: *noperms
  fakejoin:
    aliases: [fj]
    permission: elytracore.fakejoin
    permission-message: *noperms
  fakequit:
    aliases: [fq,fl,fakeleave]
    permission: elytracore.fakequit
    permission-message: *noperms
  feed:
    permission: elytracore.feed
    permission-message: *noperms
  fly:
    permission: elytracore.fly
    permission-message: *noperms
  heal:
    permission: elytracore.heal
    permission-message: *noperms
  help:
    aliases: [?,plugin,pl,version,ver]
  invisible:
    aliases: [ invis ]
    permission: elytracore.invisible
    permission-message: *noperms
  invsee:
    permission: elytracore.invsee
    permission-message: *noperms
  names:
    permission: elytracore.names
    permission-message: *noperms
  personalclearchat:
    aliases: [playerclearchat,pcc]
  punish:
    permission: elytracore.punish
    permission-message: *noperms
  rename:
    permission: elytracore.rename
    permission-message: *noperms
  rules:
    description: Shows the server rules.
  speed:
    permission: elytracore.speed
    permission-message: *noperms
  uuid:
    permission: elytracore.uuid
    permission-message: *noperms
  vanish:
    aliases: [v]
    permission: elytracore.vanish
    permission-message: *noperms
  workbench:
    aliases: [wb,craft]
    permission: elytracore.workbench
    permission-message: *noperms