main: net.elytrapvp.elytracore.ElytraCore

name: ElytraCore
api-version: 1.15
version: 1.0
author: ElytraPvP

commands:
  afk:
    usage: /<command>
    description: Set yourself as afk.
  clearchat:
    usage: /<command>
    description: Clear the chat
    aliases: [cc]
  discord:
    usage: /<command>
    description: View the server's discord.
    aliases: [dc]
  ecsee:
    usage: /<command> [player]
    description: View a player's ender chest.
  feed:
    usage: /<command>
    description: Feed yourself.
  fly:
    usage: /<command> [player]
    description: Enable or disable fly.
    aliases: [f]
  gamemode:
    usage: /<command>
    description: Change your gamemode.
    aliases: [gm]
  gamemode0:
    usage: /<command>
    description: Change your gamemode.
    aliases: [gms, gm0]
  gamemode1:
    usage: /<command>
    description: Change your gamemode.
    aliases: [gmc, gm1]
  gamemode2:
    usage: /<command>
    description: Change your gamemode.
    aliases: [gma, gm2]
  gamemode3:
    usage: /<command>
    description: Change your gamemode.
    aliases: [gmsp, gm3]
  getip:
    usage: /<command>
    description: Get a player's ip address.
    aliases: [ip]
  heal:
    usage: /<command>
    description: Heal yourself
  invsee:
    usage: /<command> [player]
    description: View a player's inventory.
  list:
    usage: /<command>
    description: View online players.
    aliases: [online, players]
  pcc:
    usage: /<command>
    description: Clear your personal chat.
  tpa:
    usage: /<command>
    description: Request to teleport to someone.
  tpaccept:
    usage: /<command>
    description: Accept a teleport request.
  tpdeny:
    usage: /<command>
    description: Deny a teleport request.
  uuid:
    usage: /<command>
    description: Get a player's uuid.