name: ElytraCore
version: 1.0
main: net.elytrapvp.elytracore.ElytraCore
api-version: 1.16
website: http://www.elytrapvp.met

commands:
  chatlog:
    aliases: [cl]
  clearchat:
    aliases: [cc]
  personalclearchat:
    aliases: [playerclearchat,pcc]

  broadcast:
    aliases: [bc,announce,a]
  feed:
  heal:
  rename:

  alts:
  ecsee:
  fly:
  invsee:
  names:
  uuid: